SHELL := /bin/bash

.PHONY: windows 


windows:
	CGO_ENABLED="1" \
	CC="/usr/bin/x86_64-w64-mingw32-gcc" \
	GOOS="windows" \
	CGO_LDFLAGS="-lmingw32 -lSDL2" \
	CGO_CFLAGS="-D_REENTRANT" \
	go build -x pong.go
